#!/usr/bin/env python3
"""Converts BDF bitmap fonts into src/font_data.c.

The fonts are the public-domain "misc-fixed" Unicode fonts maintained by
Markus Kuhn: https://www.cl.cam.ac.uk/~mgk25/ucs-fonts.html

    tools/genfont.py 5x7=5x7.bdf 6x10=6x10.bdf 7x13=7x13.bdf:6x10.bdf 9x15=9x15.bdf:6x10.bdf \\
        > src/font_data.c

"name=font.bdf:limit.bdf" keeps only the characters that limit.bdf also has,
which stops the larger fonts from dragging in scripts the small ones lack.

Every glyph becomes (width + 7) / 8 bytes per pixel row, most significant
bit leftmost, placed in a full character cell so the renderer needs no
per-glyph metrics.
"""
import re
import sys


def encodings(path):
    text = open(path, encoding="latin-1").read()
    return {int(code) for code in re.findall(r"^ENCODING (-?\d+)", text, re.M)}


def convert(name, path, limit):
    text = open(path, encoding="latin-1").read()
    cell_w, cell_h = map(int, re.search(r"^FONTBOUNDINGBOX (\d+) (\d+)", text, re.M).groups())
    ascent = int(re.search(r"^FONT_ASCENT (\d+)", text, re.M).group(1))
    row_bytes = (cell_w + 7) // 8

    glyphs = {}
    for char in text.split("STARTCHAR")[1:]:
        code = int(re.search(r"^ENCODING (-?\d+)", char, re.M).group(1))
        if code < 0x20 or code > 0xFFFF or (limit is not None and code not in limit):
            continue
        w, h, x, y = map(int, re.search(r"^BBX (-?\d+) (-?\d+) (-?\d+) (-?\d+)", char, re.M).groups())
        rows = char.split("BITMAP\n")[1].split("ENDCHAR")[0].split()
        cell = [0] * cell_h
        for r, hexrow in enumerate(rows[:h]):
            # Left-align the row in row_bytes bytes, then shift it to its column.
            bits = int(hexrow, 16) << (row_bytes * 8) >> (len(hexrow) * 4)
            target = ascent - (y + h) + r
            if 0 <= target < cell_h and x >= 0:
                cell[target] = (bits >> x) & ((1 << row_bytes * 8) - 1)
        glyphs[code] = cell

    # Height of a capital letter, used to match fonts to label sizes.
    cap = sum(1 for row in glyphs[ord("H")] if row)

    codes = sorted(glyphs)
    out = [f"/* {path.split('/')[-1]}: {len(codes)} glyphs in {cell_w}x{cell_h} cells */"]
    out.append(f"static const unsigned short codes_{name}[] = {{")
    for i in range(0, len(codes), 12):
        out.append("    " + ", ".join(f"0x{c:04X}" for c in codes[i:i + 12]) + ",")
    out.append("};")
    out.append(f"static const unsigned char rows_{name}[] = {{")
    for c in codes:
        data = b"".join(row.to_bytes(row_bytes, "big") for row in glyphs[c])
        out.append("    " + ",".join(f"0x{b:02X}" for b in data) + ",")
    out.append("};")
    out.append(f"const GfxFont font_{name} = {{ {cell_w}, {cell_h}, {ascent}, {cap}, {len(codes)}, "
               f"codes_{name}, rows_{name} }};")
    return "\n".join(out)


print("/* Generated by tools/genfont.py from public-domain misc-fixed fonts. Do not edit. */")
print('#include "gfx.h"\n')
for arg in sys.argv[1:]:
    name, paths = arg.split("=", 1)
    path, _, limit = paths.partition(":")
    print(convert(name, path, encodings(limit) if limit else None) + "\n")
